/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GoalId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Goal = IDL.Record({
  'id' : GoalId,
  'title' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'isArchived' : IDL.Bool,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'archiveGoal' : IDL.Func([GoalId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createGoal' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'getActiveGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getArchivedGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGoalsForDay' : IDL.Func(
      [Time],
      [IDL.Vec(IDL.Tuple(Goal, IDL.Bool))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleGoalCompletion' : IDL.Func([GoalId, Time], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GoalId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Goal = IDL.Record({
    'id' : GoalId,
    'title' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'isArchived' : IDL.Bool,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'archiveGoal' : IDL.Func([GoalId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createGoal' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'getActiveGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getArchivedGoals' : IDL.Func([], [IDL.Vec(Goal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGoalsForDay' : IDL.Func(
        [Time],
        [IDL.Vec(IDL.Tuple(Goal, IDL.Bool))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleGoalCompletion' : IDL.Func([GoalId, Time], [], []),
  });
};

export const init = ({ IDL }) => { return []; };